version: '0'
services:
  main_api:
    build: ./api
    ports:
      - "3030:3030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=3030
      - JWT_SECRET_KEY=1aa9eb86-c942-431c-878a-c3f718d33e37
      - ACCESS_API_KEY=0b26aee8-9dc9-4fc1-871c-3bc8bc0e47b6
      - DRAWER_API_URL=http://host.docker.internal:3050

  bff_auth:
    build: ./auth/backend
    ports:
      - "3040:3040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - main_api
    environment:
      - PORT=3040
      - API_KEY=0b26aee8-9dc9-4fc1-871c-3bc8bc0e47b6
      - API_URL=http://host.docker.internal:3030

  bff_drawer:
    build: ./drawer/backend
    ports:
      - "3050:3050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - main_api
    environment:
      - PORT=3050
      - JWT_SECRET_KEY=1aa9eb86-c942-431c-878a-c3f718d33e37
      - API_KEY=0b26aee8-9dc9-4fc1-871c-3bc8bc0e47b6
      - API_URL=http://host.docker.internal:3030

  bff_videos:
    build: ./videos/backend
    ports:
      - "3060:3060"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - main_api
    environment:
      - PORT=3060
      - JWT_SECRET_KEY=1aa9eb86-c942-431c-878a-c3f718d33e37
      - YOUTUBE_API_KEY=AIzaSyD4FXC0LCndygpt0-jbVYr5LB1R7K-7vJg
      #- YOUTUBE_API_KEY=AIzaSyBRVoy99TklRvNtQ-b_iEynjqUEF2dbqfU
      - API_KEY=0b26aee8-9dc9-4fc1-871c-3bc8bc0e47b6
      - API_URL=http://host.docker.internal:3030

  mf_main:
    build: ./main
    ports:
      - "4030:4030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mf_auth
      - mf_drawer
      - mf_videos

  mf_auth:
    build: ./auth/frontend
    ports:
      - "4040:4040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bff_auth

  mf_drawer:
    build: ./drawer/frontend
    ports:
      - "4050:4050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bff_drawer

  mf_videos:
    build: ./videos/frontend
    ports:
      - "4060:4060"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bff_videos
